fineract:
  enabled: true
  db: cloud-sql-proxy
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "test"
  image: ""
  spec: 
    template:
      spec:
        containers:
          env:
            FINERACT_DEFAULT_TENANTDB_IDENTIFIER: ""
            FINERACT_DEFAULT_TENANTDB_NAME: ""
            FINERACT_DEFAULT_TENANTDB_HOSTNAME: 127.0.0.1
            FINERACT_DEFAULT_TENANTDB_PORT: 3306
            FINERACT_HIKARI_PASSWORD: ""
            FINERACT_DEFAULT_TENANTDB_PWD: ""
            FINERACT_HIKARI_USERNAME: ""
            FINERACT_ADMIN_USERNAME: ""
            FINERACT_HIKARI_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
            FINERACT_HIKARI_JDBC_URL: "jdbc:mysql://127.0.0.1:3306/fineract_tenants?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sessionVariables=time_zone='-00:00'"
            FINERACT_SERVER_PORT: 8080
            CONTAINER_PORT: 80
  preStopScript: 'echo -e "******Fineract is stopping********";'
  ingress:
    enabled: true
    hostname: "api.ekesha.org"
    path: "/fineract-provider"
    #wildcardhostname: "*.kemetstax.org"
    annotations:
      # This tells Google Cloud to associate the External Load Balancer with the static IP which we created earlier
      # kubernetes.io/ingress.global-static-ip-name: ekesha-static-ip-d06d1de9
      # networking.gke.io/managed-certificates: ekesha-ssl-cert-d06d1de9
      # kubernetes.io/ingress.class: "nginx"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # This tells Google Cloud to create an External Load Balancer to realize this Ingress
      kubernetes.io/ingress.class: "gce"
      #nginx.org/redirect-to-https: "true"
      # kubernetes.io/ingress.allow-http: "true"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"